sudo: required
dist: xenial
language: go
go:
  - "1.11.5"

addons:
  apt:
    packages:
     - mingw-w64
     - gcc-aarch64-linux-gnu
     - g++-aarch64-linux-gnu
     - gcc-arm-linux-gnueabihf
     - g++-arm-linux-gnueabihf

notifications:
  email: false

env:
  - GO111MODULE=on

before_install:
  - make download-tools
  - GO111MODULE=off go get gopkg.in/mikefarah/yq.v2

script:
  - make check

before_deploy:
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      for TARGET in master 44f905d; do
        TARGET_GO_VERSION=$(curl -fsSL "https://raw.githubusercontent.com/gotify/server/$TARGET/.travis.yml" | yq.v2 read - go\[0\]);
        eval "$(gimme ${TARGET_GO_VERSION})";
                                                               CGO_ENABLED=1 GOOS=linux   GOARCH=amd64       make GOTIFY_VERSION=${TARGET} build;
        CC=aarch64-linux-gnu-gcc   CXX=aarch64-linux-gnu-g++   CGO_ENABLED=1 GOOS=linux   GOARCH=arm64       make GOTIFY_VERSION=${TARGET} build;
        CC=arm-linux-gnueabihf-gcc CXX=arm-linux-gnueabihf-g++ CGO_ENABLED=1 GOOS=linux   GOARCH=arm GOARM=7 make GOTIFY_VERSION=${TARGET} build;
      done
      ls -lath build;
    fi

deploy:
  - provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: build/*.so
    skip_cleanup: true
    on:
      tags: true
